apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bizify-api
  namespace: default
  labels:
    app: bizify-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bizify-api
