apiVersion: v1
kind: ServiceAccount
metadata:
  name: bizify-api
  namespace: default
  labels:
    app: bizify-api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bizify-api
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bizify-api
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bizify-api
subjects:
- kind: ServiceAccount
  name: bizify-api
  namespace: default
