"""hash_otp

Revision ID: 0144b507c449
Revises: 95650a7bcebd
Create Date: 2026-04-23 04:34:21.980143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0144b507c449'
down_revision: Union[str, None] = '95650a7bcebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_hash', sa.String(), nullable=False))
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
        batch_op.drop_column('otp_hash')

    # ### end Alembic commands ###
