"""Sync with GUID

Revision ID: 239000f30fd1
Revises: 
Create Date: 2026-02-21 11:24:13.717618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.types import CHAR, TypeDecorator


class GUID(TypeDecorator):
    """Migration-local GUID type to avoid runtime package imports."""

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID())
        return dialect.type_descriptor(CHAR(32))



# revision identifiers, used by Alembic.
revision: str = '239000f30fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=True),
    sa.Column('owner_id', GUID(), nullable=False),
    sa.Column('stage', sa.Enum('EARLY', 'BUILDING', 'SCALING', name='businessstage'), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id')
    )
    op.create_table('ideas',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'CONVERTED', name='ideastatus'), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ENTREPRENEUR', 'MENTOR', 'SUPPLIER', 'MANUFACTURER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key(
            "fk_businesses_owner_id_users",
            "businesses",
            "users",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )
        op.create_foreign_key(
            "fk_ideas_owner_id_users",
            "ideas",
            "users",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )
        op.create_foreign_key(
            "fk_businesses_idea_id_ideas",
            "businesses",
            "ideas",
            ["idea_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.create_table('admin_action_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('admin_id', GUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=False),
    sa.Column('target_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_collaborators',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='collaboratorrole'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_invites',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitestatus'), nullable=True),
    sa.Column('invited_by', GUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_invites_token'), 'business_invites', ['token'], unique=True)
    op.create_table('business_roadmaps',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('idea_id', GUID(), nullable=True),
    sa.Column('session_type', sa.Enum('IDEA_CHAT', 'BUSINESS_CHAT', 'STAGE_CHAT', 'GENERAL', name='chatsessiontype'), nullable=False),
    sa.Column('conversation_summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('agent_id', GUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('owner_id', GUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_accesses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_experiment', sa.Boolean(), nullable=True),
    sa.Column('assigned_job', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_comparisons',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_metrics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_profiles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('partner_type', sa.Enum('MENTOR', 'SUPPLIER', 'MANUFACTURER', name='partnertype'), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('services_json', sa.JSON(), nullable=True),
    sa.Column('experience_json', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=True),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('token_ref', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_links',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=True),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('plan_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills_json', sa.JSON(), nullable=True),
    sa.Column('interests_json', sa.JSON(), nullable=True),
    sa.Column('preferences_json', sa.JSON(), nullable=True),
    sa.Column('risk_profile_json', sa.JSON(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('business_invite_ideas',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('invite_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['business_invites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AI', name='chatrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('comparison_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('rank_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['idea_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_metrics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('comparison_id', GUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['idea_comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_requests',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('partner_id', GUID(), nullable=False),
    sa.Column('requested_by', GUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='requeststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('subscription_id', GUID(), nullable=True),
    sa.Column('payment_method_id', GUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_stages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('roadmap_id', GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.Enum('READINESS', 'RESEARCH', 'STRATEGY', 'MARKET', 'FUNCTIONS', 'ECONOMICS', 'LEGAL', 'MVP', 'BRANDING', 'GTM', 'OPERATIONS', name='stagetype'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='roadmapstagestatus'), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['business_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('stage_id', GUID(), nullable=False),
    sa.Column('agent_id', GUID(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'WARNING', name='agentrunstatus'), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['roadmap_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('agent_run_id', GUID(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('critique_json', sa.JSON(), nullable=True),
    sa.Column('threshold_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_logs')
    op.drop_table('agent_runs')
    op.drop_table('roadmap_stages')
    op.drop_table('payments')
    op.drop_table('partner_requests')
    op.drop_table('comparison_metrics')
    op.drop_table('comparison_items')
    op.drop_table('chat_messages')
    op.drop_table('business_invite_ideas')
    op.drop_table('user_profiles')
    op.drop_table('usages')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_table('payment_methods')
    op.drop_table('partner_profiles')
    op.drop_table('notifications')
    op.drop_table('idea_versions')
    op.drop_table('idea_metrics')
    op.drop_table('idea_comparisons')
    op.drop_table('idea_accesses')
    op.drop_table('files')
    op.drop_table('experiments')
    op.drop_table('embeddings')
    op.drop_table('chat_sessions')
    op.drop_table('business_roadmaps')
    op.drop_index(op.f('ix_business_invites_token'), table_name='business_invites')
    op.drop_table('business_invites')
    op.drop_table('business_collaborators')
    op.drop_table('admin_action_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint('fk_businesses_idea_id_ideas', 'businesses', type_='foreignkey')
        op.drop_constraint('fk_ideas_owner_id_users', 'ideas', type_='foreignkey')
        op.drop_constraint('fk_businesses_owner_id_users', 'businesses', type_='foreignkey')
    op.drop_table('ideas')
    op.drop_table('businesses')
    op.drop_table('agents')
    # ### end Alembic commands ###
