"""Add TeamInvite and TeamJoinRequest

Revision ID: 24e7f0713d57
Revises: 40d4854f5845
Create Date: 2026-03-24 06:06:57.472961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24e7f0713d57'
down_revision: Union[str, None] = '40d4854f5845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('marketing_enabled', sa.Boolean(), nullable=True),
    sa.Column('team_updates_enabled', sa.Boolean(), nullable=True),
    sa.Column('billing_alerts_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('invite_idea_access',
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['business_invites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invite_id', 'idea_id')
    )
    op.create_table('join_request_idea_access',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['business_join_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'idea_id')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', name='team_invite_status'), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('team_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='team_join_request_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skill_gap_reports')
    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('business_collaborators', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ideas', ['idea_id'], ['id'])

    with op.batch_alter_table('business_invites', schema=None) as batch_op:
        batch_op.drop_column('idea_id')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_business_idea_id', 'ideas', ['idea_id'], ['id'], use_alter=True)

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_idea_business_id', 'businesses', ['business_id'], ['id'], use_alter=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index('ix_notifications_user_status_expiry', ['user_id', 'status', 'expires_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('is_read')

    with op.batch_alter_table('skill_benchmarks', schema=None) as batch_op:
        batch_op.alter_column('industry_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('skill_benchmarks_skill_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_benchmarks', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('skill_benchmarks_skill_name_key'), ['skill_name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('industry_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('privacy_settings', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PUBLIC', 'PRIVATE', 'TEAM_ONLY', name='profilevisibility'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index('ix_notifications_user_status_expiry')
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_idea_business_id', type_='foreignkey')

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='exportstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_business_idea_id', type_='foreignkey')

    with op.batch_alter_table('business_join_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('business_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=True))

    with op.batch_alter_table('business_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    op.create_table('skill_gap_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('accuracy_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_outdated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skill_gap_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_gap_reports_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('skill_gap_reports_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('team_join_requests')
    op.drop_table('team_invites')
    op.drop_table('join_request_idea_access')
    op.drop_table('invite_idea_access')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
