"""add_guidance_system_tables

Revision ID: 2523e70147e6
Revises: 1cba93387549
Create Date: 2026-03-16 14:56:51.470379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2523e70147e6'
down_revision: Union[str, None] = '1cba93387549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidance_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_order')
    )
    op.create_table('guidance_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('concept_explanation', sa.Text(), nullable=False),
    sa.Column('platform_support_explanation', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['guidance_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_concept_mappings',
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['guidance_concepts.id'], ),
    sa.PrimaryKeyConstraint('feature_key')
    )
    op.create_table('user_concept_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_viewed_concept_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_viewed_concept_id'], ['guidance_concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_concept_states')
    op.drop_table('feature_concept_mappings')
    op.drop_table('guidance_concepts')
    op.drop_table('guidance_stages')
    # ### end Alembic commands ###
