"""add_password_reset_tokens_table

Revision ID: 2f0cced2ae5d
Revises: 7360a01ac5de
Create Date: 2026-02-23 13:36:59.438025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.types import CHAR, TypeDecorator

class GUID(TypeDecorator):
    """Migration-local GUID type to avoid runtime package imports."""
    impl = CHAR
    cache_ok = True
    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID())
        return dialect.type_descriptor(CHAR(32))

# revision identifiers, used by Alembic.
revision: str = '2f0cced2ae5d'
down_revision: Union[str, None] = '7360a01ac5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_jti'), 'password_reset_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_used'), 'password_reset_tokens', ['used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('embeddings', 'vector',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('experiments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('idea_metrics', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('idea_metrics', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('experiments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('embeddings', 'vector',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_jti'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
