"""add_questionnaire_fields_clean

Revision ID: 334d2828d10c
Revises: cd14dc97a8b0
Create Date: 2026-03-13 22:45:08.476851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334d2828d10c'
down_revision: Union[str, None] = 'cd14dc97a8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('background_json', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('personality_json', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('personalization_profile', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'background_json')
    op.drop_column('user_profiles', 'personality_json')
    op.drop_column('user_profiles', 'personalization_profile')
    # ### end Alembic commands ###
