"""add_skill_categories_and_predefined_skills

Revision ID: 348959c62ac7
Revises: 0144b507c449
Create Date: 2026-04-25 00:56:37.649893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348959c62ac7'
down_revision: Union[str, None] = '0144b507c449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('predefined_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('idea_results')
    op.drop_table('questionnaire_outputs')
    op.drop_table('profile_results')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_runs_user_id')

    op.drop_table('pipeline_runs')
    op.drop_table('problems_results')
    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.drop_constraint('account_verifications_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.drop_constraint('admin_action_logs_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('audit_logs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('businesses_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('chat_sessions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint('experiments_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('export_jobs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('files_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('group_invites', schema=None) as batch_op:
        batch_op.drop_constraint('group_invites_invited_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['invited_by'], ['id'])

    with op.batch_alter_table('idea_comparisons', schema=None) as batch_op:
        batch_op.drop_constraint('idea_comparisons_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('idea_metrics', schema=None) as batch_op:
        batch_op.drop_constraint('idea_metrics_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('idea_versions', schema=None) as batch_op:
        batch_op.drop_constraint('idea_versions_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_constraint('ideas_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('partner_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('partner_profiles_approved_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('partner_profiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('partner_requests', schema=None) as batch_op:
        batch_op.drop_constraint('partner_requests_requested_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['requested_by'], ['id'])

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint('payment_methods_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_constraint('security_logs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_constraint('share_links_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('usages', schema=None) as batch_op:
        batch_op.drop_constraint('usages_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_concept_states', schema=None) as batch_op:
        batch_op.drop_constraint('user_concept_states_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('user_profiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        # Add as nullable first so existing rows don't violate the NOT NULL constraint
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('predefined_skill_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'predefined_skills', ['predefined_skill_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'skill_categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('declared_level')

    # Backfill existing rows: old skills were all manually entered → is_custom = False
    op.execute("UPDATE user_skills SET is_custom = FALSE WHERE is_custom IS NULL")

    # Now enforce NOT NULL
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.alter_column('is_custom', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declared_level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('predefined_skill_id')
        batch_op.drop_column('is_custom')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_profiles_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_concept_states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_concept_states_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usages_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscriptions_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('share_links_created_by_fkey', 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('security_logs_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_methods_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('partner_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('partner_requests_requested_by_fkey', 'users', ['requested_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('partner_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('partner_profiles_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('partner_profiles_approved_by_fkey', 'users', ['approved_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ideas_owner_id_fkey', 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('idea_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('idea_versions_created_by_fkey', 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('idea_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('idea_metrics_created_by_fkey', 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('idea_comparisons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('idea_comparisons_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('group_invites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_invites_invited_by_fkey', 'users', ['invited_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('files_owner_id_fkey', 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('export_jobs_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('experiments_created_by_fkey', 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_sessions_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('businesses_owner_id_fkey', 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('audit_logs_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_action_logs_admin_id_fkey', 'users', ['admin_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('account_verifications_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_table('problems_results',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='problems_results_pkey')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pipeline_runs_pkey')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index('ix_pipeline_runs_user_id', ['user_id'], unique=False)

    op.create_table('profile_results',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='profile_results_pkey')
    )
    op.create_table('questionnaire_outputs',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='questionnaire_outputs_pkey')
    )
    op.create_table('idea_results',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_idea', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chat_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='idea_results_pkey')
    )
    op.drop_table('predefined_skills')
    op.drop_table('skill_categories')
    # ### end Alembic commands ###
