"""add budget, skills, and feasibility to ideas

Revision ID: 3d2f43301451
Revises: ecdbd155b90e
Create Date: 2026-04-04 02:57:21.738226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2f43301451'
down_revision: Union[str, None] = 'ecdbd155b90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('feasibility', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('feasibility')
        batch_op.drop_column('skills')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
