"""Add global soft deletes, timestamps, and plan description

Revision ID: 54033c1a85e8
Revises: c420a8a9fc2f
Create Date: 2026-02-25 06:40:56.679471

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = '54033c1a85e8'
down_revision: Union[str, None] = 'c420a8a9fc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('admin_action_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('admin_action_logs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('admin_action_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_admin_action_logs_is_deleted'), 'admin_action_logs', ['is_deleted'], unique=False)
    op.add_column('business_collaborators', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_collaborators', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_collaborators', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('business_collaborators', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_business_collaborators_is_deleted'), 'business_collaborators', ['is_deleted'], unique=False)
    op.add_column('business_invite_ideas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_invite_ideas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_invite_ideas', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('business_invite_ideas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_business_invite_ideas_is_deleted'), 'business_invite_ideas', ['is_deleted'], unique=False)
    op.add_column('business_invites', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_invites', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('business_invites', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_business_invites_is_deleted'), 'business_invites', ['is_deleted'], unique=False)
    op.add_column('business_roadmaps', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('business_roadmaps', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('business_roadmaps', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_business_roadmaps_is_deleted'), 'business_roadmaps', ['is_deleted'], unique=False)
    op.add_column('businesses', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('businesses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_businesses_is_deleted'), 'businesses', ['is_deleted'], unique=False)
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_messages', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chat_messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_messages_is_deleted'), 'chat_messages', ['is_deleted'], unique=False)
    op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_sessions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chat_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_sessions_is_deleted'), 'chat_sessions', ['is_deleted'], unique=False)
    op.add_column('email_verification_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('email_verification_tokens', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('email_verification_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_email_verification_tokens_is_deleted'), 'email_verification_tokens', ['is_deleted'], unique=False)
    op.add_column('experiments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('experiments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('experiments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_experiments_is_deleted'), 'experiments', ['is_deleted'], unique=False)
    op.add_column('idea_accesses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('idea_accesses', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('idea_accesses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_idea_accesses_is_deleted'), 'idea_accesses', ['is_deleted'], unique=False)
    op.add_column('idea_metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('idea_metrics', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('idea_metrics', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('idea_metrics', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_idea_metrics_is_deleted'), 'idea_metrics', ['is_deleted'], unique=False)
    op.drop_column('idea_metrics', 'recorded_at')
    op.add_column('idea_versions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('idea_versions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('idea_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_idea_versions_is_deleted'), 'idea_versions', ['is_deleted'], unique=False)
    op.add_column('ideas', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('ideas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_ideas_is_deleted'), 'ideas', ['is_deleted'], unique=False)
    op.add_column('password_reset_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_password_reset_tokens_is_deleted'), 'password_reset_tokens', ['is_deleted'], unique=False)
    op.add_column('payment_methods', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('payment_methods', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('payment_methods', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payment_methods_is_deleted'), 'payment_methods', ['is_deleted'], unique=False)
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('payments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('payments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    op.add_column('plans', sa.Column('description', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('plans', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('plans', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_plans_is_deleted'), 'plans', ['is_deleted'], unique=False)
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_is_deleted'), 'refresh_tokens', ['is_deleted'], unique=False)
    op.add_column('roadmap_stages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roadmap_stages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roadmap_stages', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('roadmap_stages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_roadmap_stages_is_deleted'), 'roadmap_stages', ['is_deleted'], unique=False)
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscriptions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('subscriptions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_subscriptions_is_deleted'), 'subscriptions', ['is_deleted'], unique=False)
    op.add_column('usages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usages', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_usages_is_deleted'), 'usages', ['is_deleted'], unique=False)
    op.add_column('user_profiles', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_profiles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_profiles_is_deleted'), 'user_profiles', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)

def downgrade() -> None:
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_user_profiles_is_deleted'), table_name='user_profiles')
    op.drop_column('user_profiles', 'deleted_at')
    op.drop_column('user_profiles', 'is_deleted')
    op.drop_index(op.f('ix_usages_is_deleted'), table_name='usages')
    op.drop_column('usages', 'deleted_at')
    op.drop_column('usages', 'is_deleted')
    op.drop_column('usages', 'updated_at')
    op.drop_column('usages', 'created_at')
    op.drop_index(op.f('ix_subscriptions_is_deleted'), table_name='subscriptions')
    op.drop_column('subscriptions', 'deleted_at')
    op.drop_column('subscriptions', 'is_deleted')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_index(op.f('ix_roadmap_stages_is_deleted'), table_name='roadmap_stages')
    op.drop_column('roadmap_stages', 'deleted_at')
    op.drop_column('roadmap_stages', 'is_deleted')
    op.drop_column('roadmap_stages', 'updated_at')
    op.drop_column('roadmap_stages', 'created_at')
    op.drop_index(op.f('ix_refresh_tokens_is_deleted'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('refresh_tokens', 'is_deleted')
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_index(op.f('ix_plans_is_deleted'), table_name='plans')
    op.drop_column('plans', 'deleted_at')
    op.drop_column('plans', 'is_deleted')
    op.drop_column('plans', 'updated_at')
    op.drop_column('plans', 'created_at')
    op.drop_column('plans', 'description')
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_column('payments', 'deleted_at')
    op.drop_column('payments', 'is_deleted')
    op.drop_column('payments', 'updated_at')
    op.drop_index(op.f('ix_payment_methods_is_deleted'), table_name='payment_methods')
    op.drop_column('payment_methods', 'deleted_at')
    op.drop_column('payment_methods', 'is_deleted')
    op.drop_column('payment_methods', 'updated_at')
    op.drop_index(op.f('ix_password_reset_tokens_is_deleted'), table_name='password_reset_tokens')
    op.drop_column('password_reset_tokens', 'deleted_at')
    op.drop_column('password_reset_tokens', 'is_deleted')
    op.drop_column('password_reset_tokens', 'updated_at')
    op.drop_index(op.f('ix_ideas_is_deleted'), table_name='ideas')
    op.drop_column('ideas', 'deleted_at')
    op.drop_column('ideas', 'is_deleted')
    op.drop_index(op.f('ix_idea_versions_is_deleted'), table_name='idea_versions')
    op.drop_column('idea_versions', 'deleted_at')
    op.drop_column('idea_versions', 'is_deleted')
    op.drop_column('idea_versions', 'updated_at')
    op.add_column('idea_metrics', sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_idea_metrics_is_deleted'), table_name='idea_metrics')
    op.drop_column('idea_metrics', 'deleted_at')
    op.drop_column('idea_metrics', 'is_deleted')
    op.drop_column('idea_metrics', 'updated_at')
    op.drop_column('idea_metrics', 'created_at')
    op.drop_index(op.f('ix_idea_accesses_is_deleted'), table_name='idea_accesses')
    op.drop_column('idea_accesses', 'deleted_at')
    op.drop_column('idea_accesses', 'is_deleted')
    op.drop_column('idea_accesses', 'updated_at')
    op.drop_index(op.f('ix_experiments_is_deleted'), table_name='experiments')
    op.drop_column('experiments', 'deleted_at')
    op.drop_column('experiments', 'is_deleted')
    op.drop_column('experiments', 'updated_at')
    op.drop_index(op.f('ix_email_verification_tokens_is_deleted'), table_name='email_verification_tokens')
    op.drop_column('email_verification_tokens', 'deleted_at')
    op.drop_column('email_verification_tokens', 'is_deleted')
    op.drop_column('email_verification_tokens', 'updated_at')
    op.drop_index(op.f('ix_chat_sessions_is_deleted'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'deleted_at')
    op.drop_column('chat_sessions', 'is_deleted')
    op.drop_column('chat_sessions', 'updated_at')
    op.drop_index(op.f('ix_chat_messages_is_deleted'), table_name='chat_messages')
    op.drop_column('chat_messages', 'deleted_at')
    op.drop_column('chat_messages', 'is_deleted')
    op.drop_column('chat_messages', 'updated_at')
    op.drop_index(op.f('ix_businesses_is_deleted'), table_name='businesses')
    op.drop_column('businesses', 'deleted_at')
    op.drop_column('businesses', 'is_deleted')
    op.drop_index(op.f('ix_business_roadmaps_is_deleted'), table_name='business_roadmaps')
    op.drop_column('business_roadmaps', 'deleted_at')
    op.drop_column('business_roadmaps', 'is_deleted')
    op.drop_column('business_roadmaps', 'updated_at')
    op.drop_index(op.f('ix_business_invites_is_deleted'), table_name='business_invites')
    op.drop_column('business_invites', 'deleted_at')
    op.drop_column('business_invites', 'is_deleted')
    op.drop_column('business_invites', 'updated_at')
    op.drop_index(op.f('ix_business_invite_ideas_is_deleted'), table_name='business_invite_ideas')
    op.drop_column('business_invite_ideas', 'deleted_at')
    op.drop_column('business_invite_ideas', 'is_deleted')
    op.drop_column('business_invite_ideas', 'updated_at')
    op.drop_column('business_invite_ideas', 'created_at')
    op.drop_index(op.f('ix_business_collaborators_is_deleted'), table_name='business_collaborators')
    op.drop_column('business_collaborators', 'deleted_at')
    op.drop_column('business_collaborators', 'is_deleted')
    op.drop_column('business_collaborators', 'updated_at')
    op.drop_column('business_collaborators', 'created_at')
    op.drop_index(op.f('ix_admin_action_logs_is_deleted'), table_name='admin_action_logs')
    op.drop_column('admin_action_logs', 'deleted_at')
    op.drop_column('admin_action_logs', 'is_deleted')
    op.drop_column('admin_action_logs', 'updated_at')