"""add_constraints_and_indexes

Revision ID: 64bda0428c70
Revises: 7a3f1acd4122
Create Date: 2026-02-24 12:47:09.110590

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64bda0428c70'
down_revision: Union[str, None] = '7a3f1acd4122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ideas_title'), 'ideas', ['title'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_ideas_title'), table_name='ideas')
    # ### end Alembic commands ###
