"""add_refresh_tokens_table

Revision ID: 7360a01ac5de
Revises: 240222_add_foreign_key_indexes
Create Date: 2026-02-23 13:25:56.253888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.types import CHAR, TypeDecorator

class GUID(TypeDecorator):
    """Migration-local GUID type to avoid runtime package imports."""
    impl = CHAR
    cache_ok = True
    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID())
        return dialect.type_descriptor(CHAR(32))

# revision identifiers, used by Alembic.
revision: str = '7360a01ac5de'
down_revision: Union[str, None] = '240222_add_foreign_key_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index('idx_agent_runs_agent_id', table_name='agent_runs')
    op.drop_index('idx_agent_runs_stage_id', table_name='agent_runs')
    op.drop_index('idx_business_collaborators_business_id', table_name='business_collaborators')
    op.drop_index('idx_business_collaborators_user_id', table_name='business_collaborators')
    op.drop_index('idx_business_invites_business_id', table_name='business_invites')
    op.drop_index('idx_business_invites_invited_by', table_name='business_invites')
    op.drop_index('idx_business_roadmaps_business_id', table_name='business_roadmaps')
    op.drop_index('idx_businesses_owner_id', table_name='businesses')
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_sessions_business_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_idea_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.alter_column('embeddings', 'vector',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),  # bypass change
               existing_nullable=False)
    op.drop_index('idx_embeddings_agent_id', table_name='embeddings')
    op.alter_column('experiments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(), # bypass
               existing_nullable=False)
    op.drop_index('idx_experiments_idea_id', table_name='experiments')
    op.drop_index('idx_files_owner_id', table_name='files')
    op.drop_index('idx_idea_accesses_idea_id', table_name='idea_accesses')
    op.drop_index('idx_idea_accesses_user_id', table_name='idea_accesses')
    op.alter_column('idea_metrics', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(), # bypass
               existing_nullable=False)
    op.drop_index('idx_idea_metrics_idea_id', table_name='idea_metrics')
    op.drop_index('idx_idea_versions_idea_id', table_name='idea_versions')
    op.drop_index('idx_ideas_owner_id', table_name='ideas')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_partner_profiles_user_id', table_name='partner_profiles')
    op.drop_index('idx_partner_requests_business_id', table_name='partner_requests')
    op.drop_index('idx_partner_requests_partner_id', table_name='partner_requests')
    op.drop_index('idx_partner_requests_requested_by', table_name='partner_requests')
    op.drop_index('idx_payment_methods_user_id', table_name='payment_methods')
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(), # bypass
               existing_nullable=False)
    op.drop_index('idx_payments_subscription_id', table_name='payments')
    op.drop_index('idx_roadmap_stages_roadmap_id', table_name='roadmap_stages')
    op.drop_index('idx_share_links_business_id', table_name='share_links')
    op.drop_index('idx_share_links_created_by', table_name='share_links')
    op.drop_index('idx_share_links_idea_id', table_name='share_links')
    op.drop_index('idx_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_usages_user_id', table_name='usages')
    op.drop_index('idx_validation_logs_agent_run_id', table_name='validation_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_validation_logs_agent_run_id', 'validation_logs', ['agent_run_id'], unique=False)
    op.create_index('idx_usages_user_id', 'usages', ['user_id'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('idx_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_share_links_idea_id', 'share_links', ['idea_id'], unique=False)
    op.create_index('idx_share_links_created_by', 'share_links', ['created_by'], unique=False)
    op.create_index('idx_share_links_business_id', 'share_links', ['business_id'], unique=False)
    op.create_index('idx_roadmap_stages_roadmap_id', 'roadmap_stages', ['roadmap_id'], unique=False)
    op.create_index('idx_payments_subscription_id', 'payments', ['subscription_id'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_index('idx_payment_methods_user_id', 'payment_methods', ['user_id'], unique=False)
    op.create_index('idx_partner_requests_requested_by', 'partner_requests', ['requested_by'], unique=False)
    op.create_index('idx_partner_requests_partner_id', 'partner_requests', ['partner_id'], unique=False)
    op.create_index('idx_partner_requests_business_id', 'partner_requests', ['business_id'], unique=False)
    op.create_index('idx_partner_profiles_user_id', 'partner_profiles', ['user_id'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_ideas_owner_id', 'ideas', ['owner_id'], unique=False)
    op.create_index('idx_idea_versions_idea_id', 'idea_versions', ['idea_id'], unique=False)
    op.create_index('idx_idea_metrics_idea_id', 'idea_metrics', ['idea_id'], unique=False)
    op.alter_column('idea_metrics', 'type',
               existing_type=sa.Enum('REVENUE', 'USERS', 'CONVERSION', 'ENGAGEMENT', 'RETENTION', 'MANUAL', 'AI_ANALYSIS', 'CUSTOM', name='metrictype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_index('idx_idea_accesses_user_id', 'idea_accesses', ['user_id'], unique=False)
    op.create_index('idx_idea_accesses_idea_id', 'idea_accesses', ['idea_id'], unique=False)
    op.create_index('idx_files_owner_id', 'files', ['owner_id'], unique=False)
    op.create_index('idx_experiments_idea_id', 'experiments', ['idea_id'], unique=False)
    op.alter_column('experiments', 'status',
               existing_type=sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='experimentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_index('idx_embeddings_agent_id', 'embeddings', ['agent_id'], unique=False)
    op.alter_column('embeddings', 'vector',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_chat_sessions_idea_id', 'chat_sessions', ['idea_id'], unique=False)
    op.create_index('idx_chat_sessions_business_id', 'chat_sessions', ['business_id'], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_businesses_owner_id', 'businesses', ['owner_id'], unique=False)
    op.create_index('idx_business_roadmaps_business_id', 'business_roadmaps', ['business_id'], unique=False)
    op.create_index('idx_business_invites_invited_by', 'business_invites', ['invited_by'], unique=False)
    op.create_index('idx_business_invites_business_id', 'business_invites', ['business_id'], unique=False)
    op.create_index('idx_business_collaborators_user_id', 'business_collaborators', ['user_id'], unique=False)
    op.create_index('idx_business_collaborators_business_id', 'business_collaborators', ['business_id'], unique=False)
    op.create_index('idx_agent_runs_stage_id', 'agent_runs', ['stage_id'], unique=False)
    op.create_index('idx_agent_runs_agent_id', 'agent_runs', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
