"""add_paymob_columns_to_payments

Revision ID: 95650a7bcebd
Revises: 43c68134d1ac
Create Date: 2026-04-13 14:59:44.072732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95650a7bcebd'
down_revision: Union[str, None] = '43c68134d1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymob_order_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paymob_transaction_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_paymob_order_id'), ['paymob_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_paymob_transaction_id'), ['paymob_transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_paymob_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_paymob_order_id'))
        batch_op.drop_column('paymob_transaction_id')
        batch_op.drop_column('paymob_order_id')

    # ### end Alembic commands ###
