"""Update models to group-centric rbac

Revision ID: 9ff2c293d115
Revises: 24e7f0713d57
Create Date: 2026-03-24 06:26:12.411527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ff2c293d115'
down_revision: Union[str, None] = '24e7f0713d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_idea_access')
    op.drop_table('collaborator_idea_access')
    op.drop_table('join_request_idea_access')
    
    # Create enum types
    sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus').create(op.get_bind(), checkfirst=True)
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='exportstatus').create(op.get_bind(), checkfirst=True)
    sa.Enum('PUBLIC', 'PRIVATE', 'TEAM_ONLY', name='profilevisibility').create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('business_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('business_collaborators_idea_id_fkey'), type_='foreignkey')
        batch_op.drop_column('role')
        batch_op.drop_column('idea_id')

    with op.batch_alter_table('business_invites', schema=None) as batch_op:
        batch_op.drop_column('requires_approval')
        batch_op.drop_column('role')

    with op.batch_alter_table('business_join_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus'),
               existing_nullable=True,
               postgresql_using='status::joinrequeststatus')
        batch_op.drop_column('role')

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='exportstatus'),
               existing_nullable=True,
               postgresql_using='status::exportstatus')

    with op.batch_alter_table('privacy_settings', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PUBLIC', 'PRIVATE', 'TEAM_ONLY', name='profilevisibility'),
               existing_nullable=True,
               postgresql_using='visibility::profilevisibility')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('privacy_settings', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('PUBLIC', 'PRIVATE', 'TEAM_ONLY', name='profilevisibility'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='exportstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('business_join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', name='collaboratorrole'), server_default=sa.text("'VIEWER'::collaboratorrole"), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='joinrequeststatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('business_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', name='collaboratorrole'), server_default=sa.text("'EDITOR'::collaboratorrole"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requires_approval', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))

    with op.batch_alter_table('business_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', name='collaboratorrole'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('business_collaborators_idea_id_fkey'), 'ideas', ['idea_id'], ['id'])

    op.create_table('join_request_idea_access',
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('join_request_idea_access_idea_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['business_join_requests.id'], name=op.f('join_request_idea_access_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'idea_id', name=op.f('join_request_idea_access_pkey'))
    )
    op.create_table('collaborator_idea_access',
    sa.Column('collaborator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collaborator_id'], ['business_collaborators.id'], name=op.f('collaborator_idea_access_collaborator_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('collaborator_idea_access_idea_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collaborator_id', 'idea_id', name=op.f('collaborator_idea_access_pkey'))
    )
    op.create_table('invite_idea_access',
    sa.Column('invite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('invite_idea_access_idea_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['business_invites.id'], name=op.f('invite_idea_access_invite_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invite_id', 'idea_id', name=op.f('invite_idea_access_pkey'))
    )
    # ### end Alembic commands ###
