"""add_paypal_fields_to_payments_and_subscriptions

Revision ID: dc3ac58cb19c
Revises: 3d2f43301451
Create Date: 2026-04-12 19:08:36.464814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3ac58cb19c'
down_revision: Union[str, None] = '3d2f43301451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_order_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paypal_capture_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_paypal_capture_id'), ['paypal_capture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_paypal_order_id'), ['paypal_order_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_subscription_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_paypal_subscription_id'), ['paypal_subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_paypal_subscription_id'))
        batch_op.drop_column('paypal_subscription_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_paypal_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_paypal_capture_id'))
        batch_op.drop_column('paypal_capture_id')
        batch_op.drop_column('paypal_order_id')

    # ### end Alembic commands ###
