"""add verification type to account verification

Revision ID: e500f69b18b9
Revises: 3c6920e45405
Create Date: 2026-03-13 16:49:03.642227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e500f69b18b9'
down_revision: Union[str, None] = '3c6920e45405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_type', sa.Enum('ACCOUNT_VERIFICATION', 'PASSWORD_RESET', name='verificationtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_verifications', schema=None) as batch_op:
        batch_op.drop_column('verification_type')
    # ### end Alembic commands ###
