"""Drop legacy team and collaborator tables

Revision ID: f0942ea381bf
Revises: 9ff2c293d115
Create Date: 2026-03-24 06:37:36.055522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0942ea381bf'
down_revision: Union[str, None] = '9ff2c293d115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_idea_access')
    op.drop_table('team_members')
    op.drop_table('team_invites')
    op.drop_table('team_join_requests')
    op.drop_table('teams')
    op.drop_table('business_join_requests')
    op.drop_table('business_collaborators')
    op.drop_table('business_invites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_join_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='team_join_request_status'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_join_requests_team_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('team_join_requests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_join_requests_pkey'))
    )
    op.create_table('team_invites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'expired', name='team_invite_status'), autoincrement=False, nullable=True),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('team_invites_invited_by_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_invites_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_invites_pkey')),
    sa.UniqueConstraint('token', name=op.f('team_invites_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('business_invites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'EXPIRED', name='invitestatus'), autoincrement=False, nullable=True),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('business_invites_business_id_fkey')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('business_invites_invited_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_invites_pkey')),
    sa.UniqueConstraint('token', name=op.f('business_invites_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('business_collaborators',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'removal_pending', name='collaboratorstatus'), server_default=sa.text("'active'::collaboratorstatus"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('business_collaborators_business_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('business_collaborators_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_collaborators_pkey'))
    )
    op.create_table('business_join_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='joinrequeststatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('business_join_requests_business_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('business_join_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_join_requests_pkey'))
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_members_team_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('team_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_members_pkey'))
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', name='collaboratorrole'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('teams_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teams_pkey'))
    )
    op.create_table('team_idea_access',
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('team_idea_access_idea_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_idea_access_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'idea_id', name=op.f('team_idea_access_pkey'))
    )
    # ### end Alembic commands ###
