#!/usr/bin/env python3
"""
🧪 Test Generator - Generate Missing Tests

Auto-generates comprehensive test files for services without tests.
Created by: Autonomous System
Priority: HIGH
"""

from pathlib import Path
from typing import List
import re

class TestGenerator:
    """Generate missing test files for services"""
    
    def __init__(self, project_root: Path):
        self.project_root = Path(project_root)
        self.services_dir = self.project_root / "services"
        self.tests_dir = self.project_root / "tests" / "unit" / "services"
    
    def find_services_without_tests(self) -> List[Path]:
        """Find service files that don't have corresponding tests"""
        missing_tests = []
        
        # Get all service files
        service_files = list(self.services_dir.rglob("*.py"))
        
        for service_file in service_files:
            if service_file.name.startswith("__"):
                continue
            
            # Determine expected test file path
            rel_path = service_file.relative_to(self.services_dir)
            test_file = self.tests_dir / rel_path.parent / f"test_{rel_path.name}"
            
            if not test_file.exists():
                missing_tests.append(service_file)
        
        return missing_tests
    
    def generate_test_file(self, service_file: Path) -> Path:
        """Generate a test file for given service"""
        # Read service file
        content = service_file.read_text()
        
        # Extract functions
        functions = self._extract_functions(content)
        
        # Generate test content
        test_content = self._generate_test_content(service_file, functions)
        
        # Determine test file path
        rel_path = service_file.relative_to(self.services_dir)
        test_file = self.tests_dir / rel_path.parent / f"test_{rel_path.name}"
        
        # Create directory if needed
        test_file.parent.mkdir(parents=True, exist_ok=True)
        
        # Write test file
        test_file.write_text(test_content)
        
        return test_file
    
    def _extract_functions(self, content: str) -> List[str]:
        """Extract function names from service code"""
        pattern = r'^def\s+([a-z_][a-z0-9_]*)\s*\('
        functions = re.findall(pattern, content, re.MULTILINE)
        
        # Filter out private functions (starting with _)
        return [f for f in functions if not f.startswith('_')]
    
    def _generate_test_content(self, service_file: Path, functions: List[str]) -> str:
        """Generate test file content"""
        service_name = service_file.stem
        module_path = self._get_module_path(service_file)
        
        content = f'''"""
Tests for {service_name}

Auto-generated by Test Generator
"""

import pytest
from unittest.mock import Mock, patch
from sqlalchemy.orm import Session

from {module_path} import (
    {self._format_imports(functions)}
)

class Test{self._to_pascal_case(service_name)}:
    """Test suite for {service_name}"""
    
'''
        
        # Generate test methods for each function
        for func in functions:
            content += self._generate_test_method(func)
            content += "\n"
        
        return content
    
    def _get_module_path(self, service_file: Path) -> str:
        """Get Python module path for import"""
        rel_path = service_file.relative_to(self.project_root)
        module_parts = list(rel_path.parts[:-1]) + [rel_path.stem]
        return ".".join(module_parts)
    
    def _format_imports(self, functions: List[str]) -> str:
        """Format function imports"""
        if not functions:
            return ""
        if len(functions) == 1:
            return functions[0]
        return ",\n    ".join(functions)
    
    def _to_pascal_case(self, snake_str: str) -> str:
        """Convert snake_case to PascalCase"""
        components = snake_str.split('_')
        return ''.join(x.title() for x in components)
    
    def _generate_test_method(self, func_name: str) -> str:
        """Generate test method for a function"""
        return f'''    def test_{func_name}_success(self, db_session: Session):
        """Test {func_name} - happy path"""
        # TODO: Implement test
        # Arrange
        # Act
        # Assert
        pass
    
    def test_{func_name}_invalid_input(self, db_session: Session):
        """Test {func_name} - invalid input"""
        # TODO: Implement test
        pass
    
'''

def main():
    """Generate all missing tests"""
    print("\n🧪 TEST GENERATOR - Finding Missing Tests\n")
    
    project_root = Path.cwd()
    generator = TestGenerator(project_root)
    
    # Find services without tests
    missing = generator.find_services_without_tests()
    
    print(f"Found {len(missing)} service(s) without tests:\n")
    for service in missing:
        print(f"  - {service.relative_to(project_root)}")
    
    if not missing:
        print("✅ All services have tests!")
        return
    
    print(f"\n📝 Generating tests...\n")
    
    generated = []
    for service in missing:
        try:
            test_file = generator.generate_test_file(service)
            generated.append(test_file)
            print(f"✅ Generated: {test_file.relative_to(project_root)}")
        except Exception as e:
            print(f"❌ Failed for {service.name}: {e}")
    
    print(f"\n🎉 Generated {len(generated)} test file(s)!")

if __name__ == "__main__":
    main()
